apiVersion: v1
kind: Secret
metadata:
  name: spotify-secrets
  labels:
    app: spotify-wrapped
type: Opaque
stringData:
  CLIENT_ID: "xyz"
  CLIENT_SECRET: "xyz"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: spotify-wrapped
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 80;
            location / {
                # In a multi-container pod, containers share the same network namespace (localhost)
                proxy_pass http://127.0.0.1:5000;
                
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Prefix /;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-wrapped-deployment
  labels:
    app: spotify-wrapped
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotify-wrapped
  template:
    metadata:
      labels:
        app: spotify-wrapped
    spec:
      containers:
        - name: app
          image: spotify-wraped
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "production"
          volumeMounts:
            - name: secrets-volume
              mountPath: /run/secrets
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

        - name: nginx
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: secrets-volume
          secret:
            secretName: spotify-secrets